#!/bin/bash

SRC_DIR="/root/yifei/NLP_NFS_Ganesha_Assertion/nfs-ganesha/src"
BUILD_DIR="$SRC_DIR/build"

cd $SRC_DIR

if [ -d $BUILD_DIR ]; then
    rm -rf $BUILD_DIR
fi

mkdir -p $BUILD_DIR
cd $BUILD_DIR
cmake -DCMAKE_BUILD_TYPE=$MCFS_BUILD_TYPE -DUSE_FSAL_CEPH=OFF -DUSE_FSAL_PROXY=OFF -DUSE_FSAL_GPFS=OFF -DUSE_FSAL_LUSTRE=OFF -DUSE_FSAL_GLUSTER=OFF -DUSE_9P=OFF -DUSE_ADMIN_TOOLS=OFF -DUSE_LTTNG=OFF -DUSE_FSAL_RGW=OFF -DUSE_9P_RDMA=OFF -D_USE_9P_RDMA=OFF -DUSE_NFS_RDMA=OFF -DUSE_GTEST=OFF -DUSE_RADOS_RECOV=OFF -DRADOS_URLS=OFF -DSANITIZE_ADDRESS=ON ..
make -j $(nproc --all)
sudo make install
